### ISSUE TITLE
Documentation for Preview Features

### ISSUE THREAD

**Issue by halspang** [dapr/docs#1463]
**What content needs to be created or modified?**
Preview feature functionality was added in https://github.com/dapr/dapr/issues/3048 and needs to be documented. 

**Describe the solution you'd like**
Preview features as a whole should be documented/outlined and the configuration to create them should be described.

**Where should the new material be placed?**
`https://docs.dapr.io/operations/configuration/preview-features`
Linked here: https://docs.dapr.io/operations/configuration/configuration-overview/

**Additional context**
Example config:
```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: featureconfig
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"
  features:
    - name: Actor.Reentrancy
      enabled: true
    - name: Feature2
      enabled: true
```

Current preview scope is on a per app basis as the only preview feature is Actor Reentrancy. Global scope will be an additional feature and is captured here: https://github.com/dapr/dapr/issues/3104
