### ISSUE TITLE
Identical Redis configuration for persistence and pub/sub

### ISSUE THREAD

**Issue by radu-matei** [dapr/docs#157]
The [document describing how to set up Redis](https://github.com/dapr/docs/blob/master/concepts/components/redis.md#configuration) contains identical configuration for persistence and pub/sub.

By looking at a [pub/sub sample configuration](https://github.com/dapr/samples/blob/master/4.pub-sub/deploy/redis.yaml), it appears they have at least different `spec.type` properties.

Is that currently the only difference? If so, I can contribute a quick fix for this.

![image](https://user-images.githubusercontent.com/13103165/67031122-bbb5fb00-f0c5-11e9-8f6b-a97e59686296.png)

**Comment by youngbupark** [comment]
@radu-matei Nice catch. doc is wrong. Please feel free to contribute to the doc. pub/sub yaml in doc should be like below.

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.redis
  metadata:
  - name: "redisHost"
    value: "YOUR_REDIS_HOST_HERE"
  - name: "redisPassword"
    value: "YOUR_REDIS_PASSWORD_HERE"
```
