### ISSUE TITLE
Pub/Sub without CloudEvents needs to be updated to reflect CRD support for metadata

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [dapr/docs#1674]
**Describe the issue**

https://github.com/dapr/dapr/issues/3225 has been resolved by https://github.com/dapr/dapr/pull/3380 for the v1.3 release and the pub-sub docs should include an example of declaratively subscribing to raw payloads using metadata in the Subscription CRD instead of referencing the closed bug. 

**URL of the docs**
https://v1-3.docs.dapr.io/developing-applications/building-blocks/pubsub/pubsub-raw/#declaratively-subscribe-to-raw-events

**Expected content**

```yaml
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: myevent-subscription
spec:
  topic: deathStarStatus
  route: /dsstatus
  pubsubname: pubsub
  metadata:
    rawPayload: "true"
scopes:
- app1
- app2
```

**Additional context**

Optionally, the subscription CRD example in https://docs.dapr.io/developing-applications/building-blocks/pubsub/howto-publish-subscribe/ could be expanded to include `metadata`, but given the current specificity of its use case, may be better reserved for the specific raw payloads doc.
