### ISSUE TITLE
Add documentation for Input bindings specify routes

### ISSUE THREAD

**Issue by theonefx** [dapr/docs#1741]
**What content needs to be created or modified?**
inputbinding

**Describe the solution you'd like**
developer can use a custom endpoint to replace binding name if needed.
as schema below:
```yaml
name: mybinding
spec:
    type: binding.rabbitmq
    metadata:
    - name: route
       value: /onevent
```

**Where should the new material be placed?**
https://docs.dapr.io/reference/api/bindings_api/

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/dapr/pull/3566

**Additional context**
