### ISSUE TITLE
Dapr configuration of metircs has a typo.

### ISSUE THREAD

**Issue by darren-wang** [dapr/docs#1754]
In this doc: https://docs.dapr.io/operations/monitoring/metrics/metrics-overview/

it has an example of metrics configuration:

```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: default
spec:
  tracing:
    samplingRate: "1"
  metric: # mind this key, it is different from the other doc
    enabled: true
```

However, in this doc: https://docs.dapr.io/operations/configuration/configuration-overview/#metrics

it says that the key is `metrics` instead of `metric`:

```yaml
metrics:
  enabled: true
```

so, `metrics` or `metric`，which one is right?
