### ISSUE TITLE
How-To: Run Dapr in self-hosted mode with Docker - snippet for Docker Compose doesn't work

### ISSUE THREAD

**Issue by L-Sypniewski** [dapr/docs#1981]
Snippet for running Dapr with Docker Compose doesn't work

**URL of the docs**
https://docs.dapr.io/operations/hosting/self-hosted/self-hosted-with-docker

**Expected content**
Command for `nodeapp-dapr` service misses `-components-path` parameter with a value of  `/components`
At the end of the docker-compose file network has to be defined:
```
networks:
  hello-dapr:
```

**Screenshots**

**Additional context**

**Comment by msfussell** [comment]
@L-Sypniewski - Can you provide a PR for this? Not sure with network you are now referring to, since looks like this has been  addressed

**Comment by L-Sypniewski** [comment]
@msfussell - Regarding missing `components-path` it seems to have been fixed - I am not able to reproduce the issue.
As for the network - what I meant is that the example misses the top level `hello-dapr` network declaration at the end:
```yaml
version: '3'
services:
  nodeapp:
    build: ./node
    ports:
      - "50001:50001" # Dapr instances communicate over gRPC so we need to expose the gRPC port
    depends_on:
      - redis
      - placement
    networks:
      - hello-dapr
  nodeapp-dapr:
    image: "daprio/daprd:edge"
    command: [
    #  ...
     ]
    volumes:
        - "./components/:/components" # Mount our components folder for the runtime to use
    depends_on:
      - nodeapp
    network_mode: "service:nodeapp" # Attach the 
  placement:
    # .....
networks: # missing network declaration, without this `Service "nodeapp" uses an undefined network "hello-dapr"` error occurs
  hello-dapr: null
```
