### ISSUE TITLE
OTEL collector points to the wrong image version and therefor does not deploy reliably

### ISSUE THREAD

**Issue by fabistb** [dapr/docs#1997]
## In what area(s)?

> /area observability

## What version of Dapr?

> 1.4.x
> 1.5.0

## Expected Behavior
When following the instructions from docs I expect that the otel collector deploys reliably on the cluster.
https://docs.dapr.io/operations/monitoring/tracing/open-telemetry-collector-appinsights/

## Actual Behavior
To follow up the discussion from discord:
https://discord.com/channels/778680217417809931/780574672495312936/908684408905666621

Not all versions of the image are able to deploy successfully with the following error:
``` yaml 
   State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       StartError
      Message:      failed to create containerd task: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/otelcontribcol": permission denied: unknown
      Exit Code:    128 
```

## Steps to Reproduce the Problem
Follow the instructions from the dapr docs but adjust the image from:
`image: otel/opentelemetry-collector-contrib-dev:latest`
to:
`otel/opentelemetry-collector-contrib-dev:3e9c30d841ce829403b23a812f215f8f74064304`
and deploy the it to the cluster.

## Notes
The frequency in which new versions added to docker hub makes we wonder if this is the correct repository to use.
https://hub.docker.com/r/otel/opentelemetry-collector-contrib-dev/tags

## Release Note
RELEASE NOTE: otel collector changed from latest to reliable fixed version
