### ISSUE TITLE
Kubernetes secret store example definition does not provide a reference for the metadata in the definition nor explains why it's empty in the example

### ISSUE THREAD

**Issue by alexmarshallces** [dapr/docs#2389]
**What content needs to be created or modified?**
Kubernetes secret store example definition does not provide a reference for the metadata in the definition nor explains why it's empty in the example

**Describe the solution you'd like**
A complete reference for all the metadata that is required for defining a Kubernetes secret store, or a clear statement definitively informing users that none is necessary, as appears to be the case in the example.

**Where should the new material be placed?**
[In the example for creating a custom Kubernetes secret store](https://docs.dapr.io/reference/components-reference/supported-secret-stores/kubernetes-secret-store/#create-a-custom-kubernetes-secret-store-component)

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
No PR created for this.

**Additional context**
![image](https://user-images.githubusercontent.com/98354277/164738492-a94e9fdf-4d87-4d76-8650-b51a1c5ac42b.png)

**Comment by msfussell** [comment]
@alexmarshallces - Thanks for raising this issue and agree with you that more needs to be done in the usage here.

**Comment by msfussell** [comment]
In the secrets overview section, for the secrets referesh, there need to be better clarity on saying that this K8s secret store is created by default and pointing to https://docs.dapr.io/reference/components-reference/supported-secret-stores/kubernetes-secret-store/#create-a-custom-kubernetes-secret-store-component

**Comment by berndverst** [comment]
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes
  namespace: default
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
```

This is the complete example. The Kubernetes secretstore does not support metadata. The above example corresponds to the Kubernetes secret store that is loaded by Dapr when running in Kubernetes by default.

The Kubernetes secret store is only supported when running in a Kubernetes environment, and it is loaded by default without having to configure anything -- it will be exposed as a secret store with the name "kubernetes". It is possible to configure additional Kubernetes secret stores but these would essentially all be aliases for the secret store which is already loaded by default.

**Comment by nyemade-uversky** [comment]
This is really helpful - Thank you @berndverst!

As a follow up question, I noticed that the sample you shared leaves out the  `- name: ""` part referenced in the docs. Is it safe to assume that since we don't support additional metadata for the K8S state store that there's no need to include the name attribute when you're deploying this secret store (i.e., example you shared has accurate syntax, and the docs example is incorrect)?

Docs example:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mycustomsecretstore
  namespace: default
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  - name: ""
```
