### ISSUE TITLE
Fixes need in pub/sub subscriptions

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#2532]
**URL of the docs page**
https://docs.dapr.io/developing-applications/building-blocks/pubsub/subscription-methods/

Underscores in yaml file in K8s are not allowed and so this example will fail https://docs.dapr.io/developing-applications/building-blocks/pubsub/subscription-methods/#declarative-subscriptions

If should be
```
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: order
spec:
  topic: orders
  route: /checkout
  pubsubname: pubsub
scopes:
- orderprocessing
- checkout
```
