### ISSUE TITLE
Incorrect indentation of secret store configuration .yml file.

### ISSUE THREAD

**Issue by mattmazzola** [dapr/docs#2829]
## **URL of the docs page**

https://docs.dapr.io/operations/components/component-secrets/

## **How is it currently worded?**

I think there is incorrect indentation of the secret configuration .yml file
1. Specifically the `secretKeyRef` should be same as the `name` it is supplying a value for
1. The auth.secretStore should be indented as property of `auth`

```yml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: servicec-inputq-azkvsecret-asbqueue
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
  -name: connectionString
  secretKeyRef:
      name: asbNsConnString
      key: asbNsConnString
  -name: queueName
   value: servicec-inputq
auth:
secretStore: <SECRET_STORE_NAME>
```

**How should it be worded?**

```yml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: servicec-inputq-azkvsecret-asbqueue
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: asbNsConnString
        key: asbNsConnString
    - name: queueName
      value: servicec-inputq
auth:
  secretStore: <SECRET_STORE_NAME>
```

## **Screenshots**

N/A

## **Additional context**

N/A
