### ISSUE TITLE
Sample oAuth config is wrong

### ISSUE THREAD

**Issue by jjcollinge** [dapr/docs#296]
Following the oAuth2 middleware steps outlined [here](https://github.com/dapr/docs/blob/master/howto/authorization-with-oauth/README.md)
to setup a HTTP pipeline with the oAuth2 middleware will result in an error "couldn't find middleware..." because Dapr can't reconcile the dapr config to the middleware component. This is because of the check on this [line](https://github.com/dapr/dapr/blob/d17e9243b308e830649b0bf3af5f6e84fd543baf/pkg/runtime/runtime.go#L223).

As you can see it passes both the handlers type and name into `getComponent(...)` to compare against the components `spec.type` and `metadata.name` fields. The config sample in the docs only has a name which is actually set to the handlers type.

This can be fixed by changing the config to
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: pipeline
spec:
  httpPipeline:
    handlers:
    - name: oauth2
      type: middleware.http.oauth2
````

If I get time later I'll submit a PR to fix it.
