### ISSUE TITLE
Lack of clarity under the Metrics portion of documentation for configuring docker compose based systems

### ISSUE THREAD

**Issue by KrylixZA** [dapr/docs#2974]
**Describe the issue**
I am developing a system in Visual Studio using a Docker Compose project as the primary runnable object. The hope is that my compose file will spin up a Prometheus container that will scrape metrics from my dapr-based micro-services and be able to them consume them from Grafana, as per the documentation.

An example of where my confusion starts is with the Prometheus documentation: https://docs.dapr.io/operations/monitoring/metrics/prometheus/

It indicates that the `prometheus.yml` configuration file should be pointing to <http://localhost:9090> and then simply makes a note of pointing to the Dapr metrics port if not default without further clarification of what that might look. I believe I have everything configured correctly but I am not seeing any metrics come through on the Prometheus UI nor the imported Grafana dashboards.

I am unsure if this issue is somewhat related to the same reason we cannot use the Dapr dashboard unless running in K8s or if my `prometheus.yml` file is incorrectly configured. 

**URL of the docs**
<https://docs.dapr.io/operations/monitoring/metrics/prometheus/>
<https://docs.dapr.io/operations/monitoring/metrics/grafana/>

**Expected content**
Under the section [Setup prometheus locally](https://docs.dapr.io/operations/monitoring/metrics/prometheus/#setup-prometheus-locally), provide an example configuration when running with Docker and more verbose explanation of how to connect Prometheus to scrape the Dapr metrics from the various containers managed by the compose file.

**Additional context**
I am new to Prometheus and this issue could be resolved by further clarification; this is more of a question than an issue.

This may be somewhat related to the following issues:
[#2874](https://github.com/dapr/docs/issues/2874)
[#172](https://github.com/dapr/dashboard/issues/172)

**Comment by KrylixZA** [comment]
I managed to get this to work. The part that mislead me was the command "# Replace with Dapr metrics port if not default". This was a bit confusing at first.

Turns out, I needed to provide a list of all the dapr-enabled services my compose file spins up. For example, this is roughly what my `prometheus.yml` file ended up being (replaced the names with templates for PI purposes):

```YAML
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: "dapr"

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ["dapr-service-one:9090", "dapr-service-two:9090", "dapr-service-three:9090", "dapr-service-four:9090", "dapr-service-five:9090"]
```

After this, I was able to spin up the Grafana container, connect it to my Prometheus container and that allowed me to import the dashboards and monitor my system.

After getting all of that done, it felt somewhat unnecessary to a compose-based system anyway as it is a lot of manual config for something you may spin up and destroy a couple (hundred) times a day where Zipkin gives you a lot of the same with much less config and no manual steps.

As such, I think the final outcome would be a note on the docs explaining what is possible with Docker Compose but note that it is not recommended unless running in a K8s system.
