### ISSUE TITLE
Reference secrets in components documentation implies that secrets can be shared among namespaces

### ISSUE THREAD

**Issue by marcelbenz** [dapr/docs#3027]
**Describe the issue**
The documentation states that dapr enabled apps fetches secrets from `default` and non-default namespace when referenced in components as shown in the example below.

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: eventhubs
  namespace: default
spec:
  type: bindings.azure.eventhubs
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: eventhubs-secret
      key: connectionString
```
for non-default namespaces, additional resources have to be applied.

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: <NAMESPACE>
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dapr-secret-reader
  namespace: <NAMESPACE>
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
```
This documentation implies that dapr components can fetch secrets from any namespace. But this is not the case. 

I am able to verify that the secrets in the that namespace are accessible but the dapr side-car is not not able to find the secret.

```
$ kubectl auth can-i get secret -n <NAMESPACE> --as system:serviceaccount:default:default
> yes
```

**URL of the docs**
https://v1-5.docs.dapr.io/operations/components/component-secrets/#default-namespace

**Expected content**
It should be clearly described that dapr components can only access secrets that are deployed in the same namespace. The section about non-default namespace with the `Role` and `RoleBinding` resources giving a false impression. 

Or, dapr supports fetching secrets from other namespaces. 

**Additional context**
We are using `pubsub.rabbitmq` component with rabbitmq deployed in a separate namespace from the dapr enabled apps that are using the pubsub. We are following the GitOps approach using FluxCD to deploy our apps in a k8s cluster. As we cannot use the secret created by rabbitmq during installation ([bitnami rabbitmq helm chart](https://github.com/bitnami/charts/tree/main/bitnami/rabbitmq)), we have to store the secret in the git repo and deploy it in many namespaces.
