### ISSUE TITLE
Docs for new pluggable component annotation

### ISSUE THREAD

**Issue by mcandeia** [dapr/docs#3106]
**What content needs to be created or modified?**
Pluggable components examples for kubernetes

https://docs.dapr.io/operations/components/pluggable-components/pluggable-components-registration/

on the kubernetes tab we need to add an alternative version of pluggable components config, **the current version should be kept**

**Describe the solution you'd like**
currently the following yaml is being used
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
      annotations:
        dapr.io/unix-domain-socket-path: "/tmp/dapr-components-sockets" ## required, the default path where Dapr uses for registering components.
        dapr.io/app-id: "my-app"
        dapr.io/enabled: "true"
    spec:
      volumes: ## required, the sockets volume
        - name: dapr-unix-domain-socket
          emptyDir: {}
      containers:
        ### --------------------- YOUR APPLICATION CONTAINER GOES HERE -----------
        ##
        ### --------------------- YOUR APPLICATION CONTAINER GOES HERE -----------
        ### This is the pluggable component container.
        - name: component
          volumeMounts: # required, the sockets volume mount
            - name: dapr-unix-domain-socket
              mountPath: /tmp/dapr-components-sockets
          image: YOUR_IMAGE_GOES_HERE:YOUR_IMAGE_VERSION
```

We should say that "alternatively you can annotate your pods telling dapr which containers are pluggable components" and the follow yaml should be used:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
      annotations:
        dapr.io/pluggable-components: "component" ## the name of the containers that are pluggable components separated by `,`, e.g "componentA,componentB".
        dapr.io/app-id: "my-app"
        dapr.io/enabled: "true"
    spec:
      containers:
        ### --------------------- YOUR APPLICATION CONTAINER GOES HERE -----------
        ##
        ### --------------------- YOUR APPLICATION CONTAINER GOES HERE -----------
        ### This is the pluggable component container.
        - name: component
          image: YOUR_IMAGE_GOES_HERE:YOUR_IMAGE_VERSION
```

**Where should the new material be placed?**
Within the same page on the kubernetes tab

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
https://github.com/dapr/dapr/issues/5402

**Additional context**
