### ISSUE TITLE
Questions on "How-To: Share state between applications"

### ISSUE THREAD

**Issue by rudeGit** [dapr/docs#3383]
**Issue**

The sub-sections on _appid, namespace, name and none_ under **Examples** section contain incorrect information. For example:

1. The appid sub-section talks about 'myapp', yet the following curl command does not show any info with 'myapp'.
2. The namespace  sub-section talks about 'production' namespace, yet the following curl command does not show any any info with 'production' in it.
3. The name sub-section talks about appid and not 'name' 
4. etc.,

**URL of the docs**
https://docs.dapr.io/developing-applications/building-blocks/state-management/howto-share-state/

**The examples should be accurate**

**Comment by msfussell** [comment]
@rudeGit 

The examples are correct, but could be described more clearly.
For example the 

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: myredis
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: <HOST>
  - name: redisPassword
    value: <PASSWORD>
  - name: keyPrefix
    value: appid
```
This saves the key names with just appid in the name

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: myredis
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: <HOST>
  - name: redisPassword
    value: <PASSWORD>
  - name: keyPrefix
    value: name
```
This saves the key names in the statestore with just both the app namespace AND appid in the name so that state can be retrieve by different apps.

Does this make it clearer?
