### ISSUE TITLE
Pluggable components injector 

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#3502]
This proposal https://github.com/dapr/proposals/blob/main/0005-R-pluggable-components-injector.md#completion-checklist
and this issue https://github.com/dapr/dapr/pull/5935 enable pluggable components to have a managed lifecycle. 

This issue requires
1) Describing what the Pluggable components injector is and the scenarios to use this. Documenting this here https://docs.dapr.io/developing-applications/develop-components/pluggable-components/pluggable-components-overview/

2) Documenting the How to use the injector functionality. This https://github.com/dapr/proposals/blob/main/0005-R-pluggable-components-injector.md#completion-checklist. Most likely here https://docs.dapr.io/operations/components/pluggable-components-registration/

3) Updating the annotations here https://docs.dapr.io/reference/arguments-annotations-overview/ and putting them into a group together for pluggable components

**Comment by artursouza** [comment]
This is how I managed to get this feature to work. It does simplify a little how to deploy a pluggable component:

```yaml
kind: Service
apiVersion: v1
metadata:
  name: nodeapp
  labels:
    app: node
spec:
  selector:
    app: node
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "nodeapp"
        dapr.io/app-port: "3000"
        dapr.io/enable-api-logging: "true"
        dapr.io/inject-pluggable-components: "true"
    spec:
      containers:
      - name: node
        image: ghcr.io/dapr/samples/hello-k8s-node:latest
        env:
        - name: APP_PORT
          value: "3000"
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-pluggable-statestore
  annotations:
    dapr.io/component-container: >
      {
        "name": "my-component",
        "image": "artursouza/e2e-pluggable_redis-statestore:dev-linux-arm64"
      }
spec:
  type: state.redis-pluggable
  version: v1
  metadata:
  - name: redisHost
    value: redis-master:6379
  - name: redisPassword
    secretKeyRef:
      name: redis
      key: redis-password
auth:
  secretStore: kubernetes
  ```
