### ISSUE TITLE
[Dist Lock] The required parameter "spec.version" is missing from the sample component.

### ISSUE THREAD

**Issue by tanopanta** [dapr/docs#3516]
**Describe the issue**

kubectl apply failed due to missing `spec.version` of Component's sample.

**URL of the docs**

https://docs.dapr.io/developing-applications/building-blocks/distributed-lock/howto-use-distributed-lock/#configure-a-lock-component

**Expected content**

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: lockstore
spec:
  type: lock.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: <PASSWORD>
```
