### ISSUE TITLE
[1.12] Update docs for Kubernetes nameresolver

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/docs#3556]
Docs for the Kubernetes nameresolver needs to be updated to add templating. See: https://github.com/dapr/components-contrib/pull/2883

**Comment by hhunter-ms** [comment]
@ItalyPaleAle friendly bump

**Comment by hhunter-ms** [comment]
@MaxSchaefer could you add this to the docs for 1.12?

**Comment by mukundansundar** [comment]
@ItalyPaleAle Is this a correct configuration that can be set for k8s name resolver if cluster domain or template (mutually exclusive) parameters are to be set: 
```yaml
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  nameResolution:
    component: "kubernetes"
    configuration:
      "clusterDomain": "testDomain"
      "template": "{{.ID}}-{{.Data.region}}.internal:{{.Port}}"
```
