### ISSUE TITLE
Update docs on name resolution

### ISSUE THREAD

**Issue by hhunter-ms** [dapr/docs#4005]
From comment in #3991 

To help with this PR (given this is the first time we have updated name resolution in a while) there are a few other topics that need updating along with this PR.

- [x] Update the configuration overview https://docs.dapr.io/operations/configuration/configuration-overview/ to include how to set the name resolution config as you have in the Configuration format section of the component in this PR. 
   Add it as a linked heading here https://docs.dapr.io/operations/configuration/configuration-overview/#sidecar-configuration-settings and then add a section with this info, but also say that consul is an example.

    ```
    ### Configuration format

    Within the Configuration YAML, set the spec.nameResolution.component property to "sqlite", then pass configuration options in the spec.nameResolution.configuration dictionary.

    This is the basic example of a Configuration resource:

    `
    apiVersion: dapr.io/v1alpha1
    kind: Configuration 
    metadata:
      name: appconfig
    spec:
      nameResolution:
        component: "sqlite"
        version: "v1"
        configuration:
          connectionString: "/home/user/.dapr/nr.db"
    `
    ```
- [x] Update the Configuration resource spec https://docs.dapr.io/reference/resource-specs/configuration-schema/ to include name resolution settings above.

- [x] Add a link to the https://docs.dapr.io/reference/components-reference/supported-name-resolution/ topic so that users understand how to set name resolution. In effect add this:
    - `Name resolution is configured via the [Dapr Configuration]({{< ref configuration-overview.md >}}).`

- [x] Update the "Pluggable service discovery" section https://docs.dapr.io/developing-applications/building-blocks/service-invocation/service-invocation-overview/#pluggable-service-discovery to include this sentence below after this sentence "Self-hosted machines can use the mDNS name resolution component. " like this:
   `"Self-hosted machines can use the mDNS name resolution component. As an alternative to mDNS, the SQLite name resolution component can be used for running Dapr on single-node environments and for local development scenarios. Dapr sidecars that are part of the cluster store their information in a SQLite database on the local machine."`

- [x] Remove "provider spec" in the headings for K8s, Hashicorp and mDNS components. For example:
   - here https://docs.dapr.io/reference/components-reference/supported-name-resolution/setup-nr-consul/
   - here https://docs.dapr.io/reference/components-reference/supported-name-resolution/nr-kubernetes/ 
   - here https://docs.dapr.io/reference/components-reference/supported-name-resolution/nr-mdns/
