### ISSUE TITLE
Update holopin.yaml to use the docs badge

### ISSUE THREAD

**Issue by marcduiker** [dapr/docs#4104]
Update the `.github/holopin.yaml` file with the following info to set the default [Holopin badge](https://www.holopin.io/sticker/clrqf84g1199090gldi6kf00gc) for this repo:

```yaml
organization: dapr
defaultSticker: clrqf84g1199090gldi6kf00gc
stickers:
  -
    id: clrqf84g1199090gldi6kf00gc
    alias: docs-badge
```

Once this is in place, maintainers can award contributors via the Holopin Bot by mentioning the contributors' username in a PR comment when the PR is accepted: `@holopin-bot @username`
