### ISSUE TITLE
="Fatal error from runtime: failed to retrieve the initial identity certificate: error establishing connection to sentry: context canceled: connection error: desc = \"transport: authentication handshake failed: remote error: tls: no application protocol\""

### ISSUE THREAD

**Issue by chawleejay** [dapr/docs#4137]
Hello

Im running into issues when trying to install dapr to a kubernetes cluster using argo cd. 

```      
        source:
        repoURL: https://dapr.github.io/helm-charts/
        targetRevision: "1.13"
        chart: dapr
        helm:
          values: |-
            global:
              registry: ghcr.io/dapr
              tag: 'edge'
              dnsSuffix: "cluster.local"
              logAsJson: false
              imagePullPolicy: Always
            mtls:
              enabled: false
              #workloadCertTTL: 24h
              #allowedClockSkew: 15m
            sentry:
              replicaCount: 0
```

From your docs: https://docs.dapr.io/reference/arguments-annotations-overview/

Im using kubernetes annotations attached to the above values.yaml file. Im obtaining a TLS certificate error but have mtls disabled and replicaCount for the dapr-sentry config = 0.  

Error received: 

`="Fatal error from runtime: failed to retrieve the initial identity certificate: error establishing connection to sentry: context canceled: connection error: desc = \"transport: authentication handshake failed: remote error: tls: no application protocol\""`

Where is this initial certificate config read from on initial dapr installation?
