### ISSUE TITLE
pub_sub example with FastAPI

### ISSUE THREAD

**Issue by ya-boiko** [dapr/docs#4390]
**Describe the issue**
The code sample with FastAPI (`/quickstarts/pub_sub/python/sdk/order-processor-fastapi`) doesn't work quite right (maybe it's just me). `Order-processor-sdk` and `checkout-sdk` start, but `order-processor-sdk` doesn't accept messages. The Flask example works correctly

**URL of the docs**
[quickstarts/pubsub-quickstart](https://docs.dapr.io/getting-started/quickstarts/pubsub-quickstart/)

**Expected content**
`dapr.yaml`
```yaml
version: 1
common:
  resourcesPath: ../../components/
apps:
  - appID: order-processor-sdk
    appDirPath: ./order-processor-fastapi/
    appPort: 6001
    command: ["uvicorn", "app:app"]
  - appID: checkout-sdk
    appDirPath: ./checkout/
    command: ["python3", "app.py"]
```

**Screenshots**
![image](https://github.com/user-attachments/assets/05394e2f-697b-4cc0-a93a-3922338d83e6)

**Comment by ya-boiko** [comment]
The solution is to change the `order-processor-sdk` port from 6001 to 8000 and update the commands for both apps

```yaml
version: 1
common:
  resourcesPath: ../../components/
apps:
  - appID: order-processor-sdk
    appDirPath: ./order-processor-fastapi/
    appPort: 8000
    command: ["/bin/bash", "-c", "source .venv/bin/activate && uvicorn app:app"]
  - appID: checkout-sdk
    appDirPath: ./checkout/
    command: ["/bin/bash", "-c", "source .venv/bin/activate && python3 app.py"]
```
