### ISSUE TITLE
Add spec.metadata.pemContents to MySQL/MariaDB Binding 

### ISSUE THREAD

**Issue by edwardfward** [dapr/docs#4442]
**What content needs to be created or modified?**

[MySQL & MariaDB binding](https://docs.dapr.io/reference/components-reference/supported-bindings/mysql/)

Add `spec.metadata.pemContents` to the component format as follows.

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: <NAME>
spec:
  type: bindings.mysql
  version: v1
  metadata:
    - name: url # Required, define DB connection in DSN format
      value: "<CONNECTION_STRING>"
    - name: pemPath # Optional
      value: "<PEM PATH>"
    - name: pemContents # Optional
      value: "<PEM CONTENTS>"
    - name: maxIdleConns
      value: "<MAX_IDLE_CONNECTIONS>"
    - name: maxOpenConns
      value: "<MAX_OPEN_CONNECTIONS>"
    - name: connMaxLifetime
      value: "<CONNECTION_MAX_LIFE_TIME>"
    - name: connMaxIdleTime
      value: "<CONNECTION_MAX_IDLE_TIME>"
```

Add `pemContents` to spec metadata fields.

| Field         |  Required | Binding support | Details | Example |
|---------------|-----------|-----------------|---------|---------|
| `pemContents` | N      | Output          | Contents of PEM file. Used with SSL connection. Supersedes `pemPath` |  "-----BEGIN CERTIFICATE-----<br>MIIFaDCCBFCgAwIBAgISESHkvZFwK9Qz0KsXD3x8p44aMA0GCSqGSIb3DQEBCwUA<br>...<br>bbml6YXRpb252YWxzaGEyZzIuY3JsMIGgBggrBgEFBQcBAQSBkzCBkDBNBggrBgEF<br>-----END CERTIFICATE-----" |

**Describe the solution you'd like**

Adjust documentation to cover `spec.metadata.pemContents`

**Where should the new material be placed?**

[MySQL & MariaDB binding](https://docs.dapr.io/reference/components-reference/supported-bindings/mysql/) in existing tables.

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**

[Adding spec.metadata.pemContents to MySQL Binding #3620](https://github.com/dapr/components-contrib/pull/3620)

**Additional context**

No additional context to provide.
