### ISSUE TITLE
Middleware concept doc is incorrect

### ISSUE THREAD

**Issue by jjcollinge** [dapr/docs#506]
## Expected Behavior
Following the [middleware concept](https://github.com/dapr/docs/tree/e02f3c5886a78cdac68750e255e088f0b92bb7b6/concepts/middleware) doc examples should work and it should be reflective of how to use middleware.

## Actual Behavior
The example middleware config has omitted the `type` property that is required along with the `name` property for the middleware to be loaded. It also says `uppercase` and `oauth2` don't require a "config". This is confusing as they require both a config and a component in order to get loaded properly.

I suggest we update the doc to reflect this.

Example uppercase setup.

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: uppercase
spec:
  type: middleware.http.uppercase
```
```
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: pipeline
spec:
  httpPipeline:
    handlers:
    - name: uppercase
      type: middleware.http.uppercase
```
