### ISSUE TITLE
Twitter search input binding

### ISSUE THREAD

**Issue by mchmarny** [dapr/docs#548]
## Describe the proposal

Twitter binding to encapsulate Twitter search streaming API in a dapr input binding 

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: <name>
spec:
  type: bindings.twitter
  metadata:
  - name: consumerKey
    value: ''
  - name: consumerSecret
    value: ''
  - name: accessToken
    value: ''
  - name: accessSecret
    value: ''
  - name: query
    value: ''
```
Where: 

* consumerKey (required) is the Twitter API consumer key
* consumerSecret (required) is the Twitter API consumer secret
* accessToken (required) is the Twitter API access token
* accessSecret (required) is the Twitter API access secret
* query (required) is the Twitter search query (eg dapr)
