### ISSUE TITLE
Azure redis Cache  - unclear documentation

### ISSUE THREAD

**Issue by lgmorand** [dapr/docs#580]
## Expected Behavior

On the documentation to [setup a Redis Cache](https://github.com/dapr/docs/blob/master/howto/configure-redis/README.md), there is the possibility to use the managed version of it

Once created, we need to retrieve an host and a password (primary key) and then put the values within the component YAML. 

## Actual Behavior

The document tells to retrieve the host from the services running in kubernetes while we just created a managed version of it

> Creating an Azure Managed Redis Cache
    - Once your instance is created, you'll need to grab your access key. Navigate to "Access Keys" under "Settings" and copy your key.
  **Run kubectl get svc and copy the cluster IP of your redis-master.**

Should not the host be the FQDN retrieved from the portal ? MYREDIS.redis.cache.windows.net ?
Why do we need the services ? looks like we need to deploy a containerize version first to be able to use the Azure one. 

## Steps to Reproduce the Problem

Read the doc step by stop

**Comment by robinmanuelthiel** [comment]
I am sure what the docs are trying to suggest is, that you can *either* host Reddis on your cluster *or* use a managed instance like Azure Cache for Redis.

If you ask me, it's even more concerning to recommend disabling the SSL port, but that's probably a topic for a separate issue.

**Comment by yaron2** [comment]
If this is not clear, the docs should be updated.

@robinmanuelthiel there's no need to disable the SSL port as Dapr supports SSL authentication for Redis. This should probably be updated too.

/cc @orizohar

**Comment by robinmanuelthiel** [comment]
@yaron2 yep, it's not needed but the docs are suggesting that. This was concerning to me.

@lgmorand, here is what my working Azure Cache for Redis config looks like

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: rothiedaprcache.redis.cache.windows.net:6380
  - name: redisPassword
    value: xxxxxxxxxxxxxx
  - name: enableTLS   # <-- This is the important part missing in the docs
    value: "true"
```
