### ISSUE TITLE
How to configure Event Grid input binding: concrete examples?

### ISSUE THREAD

**Issue by Masahigo** [dapr/docs#604]
## Ask your question here

I have a simple use case where I'd like to test out Event Grid input binding: new blob is created and I'd use Dapr to listen to the event and notify my app (.net core web api) which would in turn execute some logic. 

I'm having problems getting started because the current documentation does not provide any concrete examples:

https://github.com/dapr/docs/blob/master/reference/specs/bindings/eventgrid.md

- **subscriberEndpoint**: Is this expecting endpoint from Dapr or my app? Why the fixed path `/api/events`?

- **handshakePort**: What is expected here?

I've pointed out these questions also here: https://github.com/dapr/docs/pull/569

**Comment by Masahigo** [comment]
Okay, I found this commit: https://github.com/dapr/components-contrib/pull/290/files

And tried to configure my Event Grid input binding like this (under _components_ folder):

**eventgrid.yml**

```yml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: eventgrid-input
  namespace: default
spec:
  type: bindings.azure.eventgrid
  metadata:
  # Required Input Binding Metadata
  - name: tenantId
    value: "xxx"
  - name: subscriptionId
    value: "xxx"
  - name: clientId
    value: "xxx"
  - name: clientSecret
    value: "xxx"
  - name: subscriberEndpoint
    value: "https://f1aac830.ngrok.io/api/events"  
  - name: handshakePort
    value: 3500
  - name: scope
    value: "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Storage/storageAccounts/xxx"
  # Optional Input Binding Metadata
  - name: eventSubscriptionName
    value: "blob-storage-subscription"
```

I also configured ngrok with following:
https://f1aac830.ngrok.io -> http://localhost:3500 

And then tried to create Event Grid subscription based on [the instructions](https://docs.microsoft.com/fi-fi/azure/storage/blobs/storage-blob-event-quickstart?toc=%2Fazure%2Fevent-grid%2Ftoc.json#subscribe-to-your-storage-account)

```bash
storageid=$(az storage account show --name $AZ_STOR_NAME --resource-group $STOR_RG_NAME --query id --output tsv)

endpoint=https://f1aac830.ngrok.io/api/events

az eventgrid event-subscription create \
  --source-resource-id $storageid \
  --name blob-storage-subscription \
  --endpoint $endpoint

If the provided endpoint does not support subscription validation handshake, navigate to the validation URL that you receive in the subscription validation event, in order to complete the event subscription creation or update. For more details, please visit http://aka.ms/esvalidation
Deployment failed. Correlation ID: xxx. Webhook validation handshake failed for https://f1aac830.ngrok.io/api/events. Http POST request failed with response code Unknown. For troublehooting, visit https://aka.ms/esvalidation. Activity id:xxx, timestamp: 5/25/2020 1:07:08 PM (UTC).
```

So the validation handshake fails but I don't see my local Dapr logging anything from this either so the request from Event Grid is not even reaching the custom webhook endpoint.

ngrok is also reporting 404

![image](https://user-images.githubusercontent.com/9364649/82816805-7c922880-9ea4-11ea-9f69-c1140df3e826.png)
