### ISSUE TITLE
Suggestion: Make use of Secrets

### ISSUE THREAD

**Issue by jellebens** [dapr/docs#670]
https://github.com/dapr/docs/blob/master/howto/configure-redis/README.md#configuring-redis-for-pubsub

Would it be possible update document to make use of secrets rather than hard-coded variables?

e.g. 
kubectl create secret generic redis --from-literal=passphrase=$REDIS_PASSWORD -n dapr-system
```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
  namespace: dapr-system
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: $REDIS_HOST
  - name: redisPassword
    secretKeyRef:
      name: redis
      key:  passphrase
```
