### ISSUE TITLE
Clarify nestedSeparator in local secret store

### ISSUE THREAD

**Issue by cecilphillip** [dapr/docs#698]
What is the purpose of the `nestedSeparator` property in the local secret store configuration? Since it's ready JSON files, the colon is already a part of the schema. It would be good to have additional examples in the docs to show its necessity. 

It would be also good to see how the usages of `secretKeyRef:key` and `secretKeyRef:name` affect the required layout of the local store.

**Comment by cecilphillip** [comment]
Here's an example.. if the secrets section of my yml file looks like the following, how would the localstore json file have to look for this to work??

```yaml
      secretKeyRef:
        name: redis
        key: redisPassword
```

**Comment by amanbha** [comment]
cc @cmendible

**Comment by cmendible** [comment]
Hi, in such a case the secrets.json would look like:

```
{
    "redis": "your redis password"
}
```

The redis configuration something like:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: "localhost:6379"
  - name: redisPassword
    secretKeyRef:
      name: redis
auth:
    secretStore: demosecrets
```

and the local store configuration:

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: demosecrets
spec:
  type: secretstores.local.localsecretstore
  metadata:
    - name: secretsFile
      value: C:\_dev\secrets.json
```

Regarding the _nestedSeparator_ param: it is used when flattening the json hierarchy to a map / dictionary. Given the following json:

```
{
    "redis": "your redis password",
    "connectionStrings": {
        "sql": "yada yada",
        "mysql": "whatever"
    }
}
```
once loaded the local secret store will hold a map with the following keys / values:

"redis" / "your redis password"
"connectionStrings:sql" / "yada yada"
"connectionStrings:mysql" / "whatever"

Hope it helps!

**Comment by cecilphillip** [comment]
@cmendible yes! that does help. Can this be added to the documentation for the local store?

**Comment by cmendible** [comment]
Sure! I can take some time next weekend to added it to the docs.

**Comment by cecilphillip** [comment]
Another thing that would be nice to cover in the updated document is how the local store uses `secretKeyRef.key`.  For an un-nested JSON file, you're only using the `secretKeyRef.name` property. Is `secretKeyRef.key` how you would access nested values?

**Comment by cmendible** [comment]
The resulting map / dictionary has no nested values and therefore you will always use the _secretKeyRef.name_. We can find a similar behavior in the secret store implementation for Azure Key Vault. 

I"ll try to clarify this in the doc.

**Comment by cecilphillip** [comment]
Right now my local secrets file looks like this

```json
{
  "redis": "S0m3P@$$w0rd"
}
```

This setup works for me. Using MacOS with Dapr 0.9.0
``` yaml
      secretKeyRef:
        name: redis
```
so does
``` yaml
      secretKeyRef:
        name: redis
        key: redis
```

but this one doesn't
``` yaml
      secretKeyRef:
        name: redis
        key: redisPassword
```
