### ISSUE TITLE
Fix azure keyvault managed identity docs cause AAD Pod Identity fields are now case sensitive

### ISSUE THREAD

**Issue by cmendible** [dapr/docs#988]
**Describe the issue**
Fix Azure Key Vault managed identity docs cause AAD Pod Identity fields are now case sensitive.

More info about this change [here](https://github.com/Azure/aad-pod-identity/tree/v1.6.0#v160-breaking-change?WT.mc_id=AZ-MVP-5002618)

**URL of the docs**
https://docs.dapr.io/operations/components/setup-secret-store/supported-secret-stores/azure-keyvault-managed-identity/

**Expected content**
Correct configuration for AzureIdentity and AzureIdentityBinding must read:

``` yaml
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: [you managed identity name]
spec:
  type: 0
  resourceID: [you managed identity id]
  clientID: [you managed identity Client ID]
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: [you managed identity name]-identity-binding
spec:
  azureIdentity: [you managed identity name]
  selector: [you managed identity selector]
```
